version: 2
updates:
  # Go modules dependencies
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "stage"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
      - "core"
    open-pull-requests-limit: 10

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "stage"
    labels:
      - "ci"
      - "dependencies"
    commit-message:
      prefix: "ci(deps)"