name: aerospike-client-go
dir: src/github.com/aerospike/aerospike-client-go/v4

container:
  - base:
      - docker.qe.aerospike.com/build/golang:1.11

build:
  - name: build
    script:
      - go get -v github.com/aerospike/aerospike-client-go/v4
      - go build -v -x github.com/aerospike/aerospike-client-go/v4
      - go install -v -x github.com/aerospike/aerospike-client-go/v4/tools/cli
      - go install -v -x github.com/aerospike/aerospike-client-go/v4/tools/benchmark
      - go install -v -x github.com/aerospike/aerospike-client-go/v4/tools/asinfo
