// Copyright 2014-2026 Aerospike, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package aerospike

import (
	"fmt"

	"github.com/aerospike/aerospike-client-go/v8/types"
)

// BinReceiver receives bin values from the read path without going through
// BinMap or reflection. Each bin in a server response is delivered via one
// AerospikeBin call. Implementations are typically code-generated for a
// specific struct shape but can be hand-written for custom destinations
// (channels, protobufs, arenas, columnar buffers).
//
// Thread safety: a single receiver instance is invoked from one goroutine
// during a single GetSink call. In BatchGetSink, the receiver at slot i is
// invoked from the goroutine handling the node that owns key i — different
// slots may be invoked concurrently. If the same receiver is passed for
// multiple slots, or if receivers share mutable state, the caller is
// responsible for synchronization.
type BinReceiver interface {
	AerospikeBin(name string, value any) Error
}

// BinReceiverNames is an optional capability. When a BinReceiver implements
// it, the client requests only the listed bins from the server. When absent,
// the client requests all bins.
type BinReceiverNames interface {
	AerospikeBinNames() []string
}

// BinReceiverMetadata is an optional capability. When a BinReceiver
// implements it, the parser delivers record metadata (generation and
// expiration) before any AerospikeBin call.
type BinReceiverMetadata interface {
	AerospikeMetadata(generation, expiration uint32) Error
}

// BinTypeMismatchError returns the error a BinReceiver should surface
// when the wire value for a bin does not match any of the types it
// knows how to decode. Code generated by aerospike-bingen emits this on
// the default branch of every per-bin type-switch.
func BinTypeMismatchError(binName string, value any, expectedType string) Error {
	return newError(types.PARAMETER_ERROR,
		fmt.Sprintf("bin %q: expected %s, got %T", binName, expectedType, value))
}
