name: Build and test against multi-node cluster

on:
  workflow_dispatch:
    inputs:
      aerospike_version:
        description: "Aerolab/Aerospike version"
        required: false
        default: "8.1.0.1"
      nodes:
        description: "Number of cluster nodes"
        required: false
        default: "3"
      cluster_name:
        description: "Cluster name"
        required: false
        default: "ce"
  push:
    branches:
      - CLIENT-3852-tests-against-multi-node-cluster
jobs:
  make-matrix:
    runs-on: ubuntu-latest
    outputs:
      input-matrix: ${{ steps.create-server-matrix.outputs.matrix }}
      go-version: ${{ steps.get-go-version.outputs.go-version }}
    steps:
      - uses: actions/checkout@v4

      - name: Get Go version
        id: get-go-version
        run: |
          echo "go-version=$(grep '^go [0-9]' go.mod | awk '{print $2}')" >> $GITHUB_OUTPUT
          
      - id: create-server-matrix
        uses: ./.github/actions/make-matrix
        with:
          default_json: |
            {
              "stable": { "version": "8.1.0.1" }
            }
          go_version: ${{ steps.get-go-version.outputs.go-version }}

      - name: debug - print input variables
        run: |
          echo "Go version: ${{ steps.get-go-version.outputs.go-version }}"
          echo 'Matrix output:'
          echo '${{ steps.create-server-matrix.outputs.matrix }}' | jq .
      
  build:
    timeout-minutes: 30
    needs: make-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.make-matrix.outputs.input-matrix) }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy Aerolab Cluster
        uses: gagan405/github-action-aerolab-runner@v1
        with:
          aerospike_version: "8.1.0.1"
          nodes: 3
          cluster_name: "ci-test"
        
      - name: "Setup Go ${{ needs.make-matrix.outputs.go-version }}"
        uses: actions/setup-go@v4
        with:
          go-version: "${{ needs.make-matrix.outputs.go-version }}"
          cache: true
      - name: Fetch dependencies
        env:
          GODEBUG: fips140=on
        run: |
          # Install all dependencies
          go mod download

          # Install ginkgo CLI and gocovmerge for testing
          go install github.com/onsi/ginkgo/v2/ginkgo@v2.22.2
          go mod download github.com/wadey/gocovmerge

          # Vendor the dependencies
          go mod vendor

      - name: Display Go version
        run: |
          echo "Go version: ${{ needs.make-matrix.outputs.go-version }}"
      - name: Run the tests
        env: {GOPROXY: off, GOSUMDB: off, GOFLAGS: -mod=vendor}
        run: go run -mod=vendor github.com/onsi/ginkgo/v2/ginkgo -coverprofile=./cover_native.out -covermode=atomic -coverpkg=./... -race -keep-going -succinct -randomize-suites -skip="HyperLogLog" -- -p=3100
      - name: Combine Cover Profiles
        env: {GOPROXY: off, GOSUMDB: off, GOFLAGS: -mod=vendor}
        run: go run -mod=vendor github.com/wadey/gocovmerge cover_*.out > cover_all.out
      - name: Check Code Coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          # Configure action using config file (option 1)
          config: ./.testcoverage.yml
