name: Aerospike Go Client Tests
"on":
  push:
  pull_request:

env:
  AEROSPIKE_HOSTS: "127.0.0.1:3000"
  GODEBUG: fips140=only
  GOFIPS140: latest
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - 1.25.1
        server-version:
          - 8.1.0.0
    steps:
      - uses: actions/checkout@v4
      - name: "Setup Go ${{ matrix.go-version }}"
        uses: actions/setup-go@v4
        with:
          go-version: "${{ matrix.go-version }}"
          cache: true
      - name: Fetch dependencies
        env:
          GODEBUG: fips140=on
        run: |
          # Install all dependencies
          go mod download

          # Install ginkgo CLI and gocovmerge for testing
          go install github.com/onsi/ginkgo/v2/ginkgo@v2.22.2
          go mod download github.com/wadey/gocovmerge

          # Vendor the dependencies
          go mod vendor

      - name: Display Go version
        run: go version
      - name: Set up Aerospike Database
        uses: reugn/github-action-aerospike@v1
        with:
          server-version: ${{ matrix.server-version }}
      - name: Test Lua Code
        env: {GOPROXY: off, GOSUMDB: off, GOFLAGS: -mod=vendor}
        run: go run -mod=vendor github.com/onsi/ginkgo/v2/ginkgo -cover -race -r -keep-going -succinct -randomize-suites internal/lua
      - name: Test types package
        env: {GOPROXY: off, GOSUMDB: off, GOFLAGS: -mod=vendor}
        run: go run -mod=vendor github.com/onsi/ginkgo/v2/ginkgo -cover -race -r -keep-going -succinct -randomize-suites types
      - name: Test pkg tests
        env: {GOPROXY: off, GOSUMDB: off, GOFLAGS: -mod=vendor}
        run: go run -mod=vendor github.com/onsi/ginkgo/v2/ginkgo -cover -race -r -keep-going -succinct -randomize-suites pkg
      - name: Build Benchmark tool
        env: {GOPROXY: off, GOSUMDB: off, GOFLAGS: -mod=vendor}
        run: cd tools/benchmark | go build -mod=vendor -tags as_proxy -o benchmark .
      - name: Build asinfo tool
        env: {GOPROXY: off, GOSUMDB: off, GOFLAGS: -mod=vendor}
        run: cd tools/asinfo | go build -mod=vendor -o asinfo .
      - name: Build cli tool
        env: {GOPROXY: off, GOSUMDB: off, GOFLAGS: -mod=vendor}
        run: cd tools/cli | go build -mod=vendor -o cli .
      - name: Build example files
        env: {GOPROXY: off, GOSUMDB: off, GOFLAGS: -mod=vendor}
        run: find examples -name "*.go" -type f -print0 | xargs -0 -n1 go build
      - name: Build with Reflection code removed
        env: {GOPROXY: off, GOSUMDB: off, GOFLAGS: -mod=vendor}
        run: go run -mod=vendor github.com/onsi/ginkgo/v2/ginkgo build -tags="as_performance" .
      - name: Build for Google App Engine (unsafe package removed)
        env: {GOPROXY: off, GOSUMDB: off, GOFLAGS: -mod=vendor}
        run: go run -mod=vendor github.com/onsi/ginkgo/v2/ginkgo build -tags="app_engine" .
      - name: Run FIPS Compliance Tests
        env: {GOPROXY: off, GOSUMDB: off, GOFLAGS: -mod=vendor}
        run: go run -mod=vendor github.com/onsi/ginkgo/v2/ginkgo -v fips_complience_test.go
      - name: Run the tests
        env: {GOPROXY: off, GOSUMDB: off, GOFLAGS: -mod=vendor}
        run: go run -mod=vendor github.com/onsi/ginkgo/v2/ginkgo -coverprofile=./cover_native.out -covermode=atomic -coverpkg=./... -race -keep-going -succinct -randomize-suites -skip="HyperLogLog"
      - name: Combine Cover Profiles
        env: {GOPROXY: off, GOSUMDB: off, GOFLAGS: -mod=vendor}
        run: go run -mod=vendor github.com/wadey/gocovmerge cover_*.out > cover_all.out
      - name: Check Code Coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          # Configure action using config file (option 1)
          config: ./.testcoverage.yml
