name: Build and test against multi-node cluster

on:
  workflow_dispatch:
    inputs:
      aerospike_version:
        description: "Aerospike version to test against"
        required: false
        default: "8.1.1"
      nodes:
        description: "Number of cluster nodes"
        required: false
        default: "3"
      runner_version:
        description: "Ubuntu runner version"
        required: false
        default: "ubuntu-24.04" # https://github.com/actions/runner-images/blob/main/README.md
      modes:
        description: "Comma-separated list of consistency modes (AP,SC). Casing matters"
        required: false
        default: "AP,SC"

permissions:
  contents: read   
  actions: read  
  id-token: write

env:
  # defaults to use against workflow triggered through cron
  AEROSPIKE_VERSION: 8.1.1
  NODES: 3
  RUNNER_VERSION: ubuntu-24.04
  MODES: AP,SC

jobs:
  make-matrix:
    runs-on: ${{ github.event_name == 'workflow_dispatch' && inputs.runner_version || 'ubuntu-24.04' }}
    outputs:
      input-matrix: ${{ steps.create-server-matrix.outputs.matrix }}
      go-version: ${{ steps.get-go-version.outputs.go-version }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9ca718d3bf646d6534007c269a635b3e54cadf99 # v2.19.2
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Get Go version
        id: get-go-version
        run: |
          echo "go-version=$(grep '^go [0-9]' go.mod | awk '{print $2}')" >> $GITHUB_OUTPUT

      - id: create-server-matrix
        uses: ./.github/actions/make-matrix
        with:
          default_json: |
            {
              "stable": { "version": "${{ github.event_name == 'workflow_dispatch' && inputs.aerospike_version || env.AEROSPIKE_VERSION }}" }
            }
          go_version: ${{ steps.get-go-version.outputs.go-version }}
          modes: ${{ github.event_name == 'workflow_dispatch' && inputs.modes || env.MODES }}

      - name: debug - print input variables
        run: |
          echo "Aerospike version: ${{ github.event_name == 'workflow_dispatch' && inputs.aerospike_version || env.AEROSPIKE_VERSION }}"
          echo "Nodes: ${{ github.event_name == 'workflow_dispatch' && inputs.nodes || env.NODES }}"
          echo "Go version: ${{ steps.get-go-version.outputs.go-version }}"
          echo "Consistency Mode: ${{ github.event_name == 'workflow_dispatch' && inputs.modes || env.MODES }}"
          echo 'Matrix output:'
          echo '${{ steps.create-server-matrix.outputs.matrix }}' | jq .

  build:
    timeout-minutes: 30
    needs: make-matrix
    runs-on: ${{ github.event_name == 'workflow_dispatch' && inputs.runner_version || 'ubuntu-24.04' }}
    permissions:
      id-token: write
      actions: write 
    strategy:
      matrix:
        include: ${{ fromJson(needs.make-matrix.outputs.input-matrix) }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9ca718d3bf646d6534007c269a635b3e54cadf99 # v2.19.2
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Aerospike multi-node cluster
        uses: aerospike/shared-workflows/.github/actions/setup-aerospike-server@5e2e7a2458e4f7c5aa0a05b0e9de8c77e0d60da6
        with:
          aerospike-version: ${{ matrix.version }}
          num-nodes: ${{ github.event_name == 'workflow_dispatch' && inputs.nodes || env.NODES }}
          base-port: 3100
          enable-strong-consistency: ${{ matrix.mode == 'SC' }}
          features-content: ${{ secrets.FEATURES_CONF }}
          oidc-provider: ${{ vars.OIDC_PROVIDER }}
          oidc-audience: ${{ vars.OIDC_AUDIENCE }}

      - name: "Setup Go ${{ needs.make-matrix.outputs.go-version }}"
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: "${{ needs.make-matrix.outputs.go-version }}"
          cache: true
      - name: Fetch dependencies
        env:
          GODEBUG: fips140=on
        run: |
          # Install all dependencies
          go mod download

          # Install ginkgo CLI and gocovmerge for testing
          go install github.com/onsi/ginkgo/v2/ginkgo@v2.22.2
          go mod download github.com/wadey/gocovmerge

          # Vendor the dependencies
          go mod vendor

      - name: Display Go version
        run: |
          echo "Go version: ${{ needs.make-matrix.outputs.go-version }}"
      - name: Run the tests
        env: {GOPROXY: off, GOSUMDB: off, GOFLAGS: -mod=vendor}
        run: go run -mod=vendor github.com/onsi/ginkgo/v2/ginkgo -output-dir=./ -coverprofile=covprofile_native.out -covermode=atomic -coverpkg=./... -race -keep-going -succinct -randomize-suites -skip="HyperLogLog" -- -hosts=127.0.0.1:3100,127.0.0.1:3101,127.0.0.1:3102 -use-services-alternate=true
      - name: Combine Cover Profiles
        env: {GOPROXY: off, GOSUMDB: off, GOFLAGS: -mod=vendor}
        run: go run -mod=vendor github.com/wadey/gocovmerge covprofile_*.out > cover_all.out
      - name: Check Code Coverage
        uses: vladopajic/go-test-coverage@a93b868a4cbcbf18dc3781650fad241f0020e609 # v2.18.8
        with:
          config: ./.testcoverage.yml
      - name: Show coverage report in step summary
        if: always()
        run: |
          {
            echo "**coverage:**"
            echo ""
            echo "**${{ matrix.version }}-${{ matrix.mode }}:** ${{ steps.check-coverage.outputs.total-coverage }}%"
          } >> "$GITHUB_STEP_SUMMARY"
      - name: Move coverage files under reports folder
        run: |
          mkdir -p reports
          mv covprofile_*.out reports/
      - name: Upload coverage report
        uses: actions/upload-artifact@v7
        with:
          name: cover_${{matrix.version}}_${{matrix.mode}}
          path: reports
          if-no-files-found: warn

  merged_coverage:
    name: Final Coverage
    needs: build
    uses: ./.github/workflows/merge-coverage.yml
    with:
      artifact_pattern: cover_*
      threshold: ${{ fromJSON(vars.COVERAGE_THRESHOLD) }}
    permissions:
      actions: write
      contents: read 
