name: Aerospike Go Client Tests
on:
  push:
  pull_request:

env:
  AEROSPIKE_HOSTS: "127.0.0.1:3000"
jobs:
  make-matrix:
    runs-on: ubuntu-latest
    outputs:
      input-matrix: ${{ steps.create-server-matrix.outputs.matrix }}
      go-version: ${{ steps.get-go-version.outputs.go-version }}
    steps:
      - uses: actions/checkout@v4

      - name: Get Go version
        id: get-go-version
        run: |
          echo "go-version=$(grep '^go [0-9]' go.mod | awk '{print $2}')" >> $GITHUB_OUTPUT
          
      - id: create-server-matrix
        uses: ./.github/actions/make-matrix
        with:
          default_json: |
            {
              "stable": { "version": "8.0.0.0" },
              "release": { "version": "7.0.1.1" }
            }
          go_version: ${{ steps.get-go-version.outputs.go-version }}

      - name: debug - print input variables
        run: |
          echo ${{ steps.get-go-version.outputs.go-version }}
          echo ${{ steps.create-server-matrix.outputs.input-matrix }}
  build:
    needs: make-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.make-matrix.outputs.input-matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: "Setup Go ${{ matrix.go-version }}"
        uses: actions/setup-go@v4
        with:
          go-version: "${{ matrix.go-version }}"
          cache: true
      - name: Display Go version
        run: |
          echo "Go version: ${{ matrix.go-version }}"

      - name: Set up Aerospike Database
        uses: reugn/github-action-aerospike@v1
        with:
          server-version: ${{ matrix.version }}
      - name: Test Lua Code
        run: go run github.com/onsi/ginkgo/v2/ginkgo -cover -race -r -keep-going -succinct -randomize-suites internal/lua
      - name: Test types package
        run: go run github.com/onsi/ginkgo/v2/ginkgo -cover -race -r -keep-going -succinct -randomize-suites types
      - name: Test pkg tests
        run: go run github.com/onsi/ginkgo/v2/ginkgo -cover -race -r -keep-going -succinct -randomize-suites pkg
      - name: Build Benchmark tool
        run: cd tools/benchmark | go build -tags as_proxy -o benchmark .
      - name: Build asinfo tool
        run: cd tools/asinfo | go build -o asinfo .
      - name: Build cli tool
        run: cd tools/cli | go build -o cli .
      - name: Build example files
        run: find examples -name "*.go" -type f -print0 | xargs -0 -n1 go build
      - name: Build with Reflection code removed
        run: go run github.com/onsi/ginkgo/v2/ginkgo build -tags="as_performance" .
      - name: Build for Google App Engine (unsafe package removed)
        run: go run github.com/onsi/ginkgo/v2/ginkgo build -tags="app_engine" .
      - name: Run the tests
        run: go run github.com/onsi/ginkgo/v2/ginkgo -coverprofile=./cover_native.out -covermode=atomic -coverpkg=./... -race -keep-going -succinct -randomize-suites -skip="HyperLogLog"
      - name: Download gocovmerge
        run: go mod download github.com/wadey/gocovmerge
      - name: Combine Cover Profiles
        run: go run github.com/wadey/gocovmerge cover_*.out > cover_all.out
      - name: Check Code Coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          # Configure action using config file (option 1)
          config: ./.testcoverage.yml
