name: Merge Code Coverage
on:
  workflow_call:
    inputs:
      artifact_pattern:
        description: 'Artifact name pattern'
        required: false
        type: string
        default: 'cover_*'
      threshold:
        description: 'Coverage threshold'
        required: false
        type: number
        default: 0

permissions:
  actions: write
  contents: read  

jobs:
  merged_coverage:
    runs-on: ${{ vars.BUILD_CONTAINER_DISTRO_VERSION }}

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Download all coverage artifacts
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          pattern: ${{ inputs.artifact_pattern }}
          path: reports

      - name: Merge coverage profiles
        run: |
          go run github.com/wadey/gocovmerge reports/**/covprofile_*.out > cover_all.out

      - name: Check Code Coverage
        id: check-coverage
        uses: vladopajic/go-test-coverage@cc5012c2cfa84542e02b079141958a885861d326 # v2.17.0
        continue-on-error: true
        with:
          config: ./.testcoverage.yml
          threshold-total: ${{ inputs.threshold }}

      - name: Show coverage summary
        if: always()
        run: |
          {
            echo "**Total coverage:** ${{ steps.check-coverage.outputs.total-coverage }}%"
            echo
            echo "<details><summary><strong>Detailed report</strong></summary>"
            echo
            echo '```text'
            echo '${{ steps.check-coverage.outputs.report }}' | jq -r .
            echo '```'
            echo "</details>"
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Generate Html report
        run: |
          mkdir -p coverage-reports
          go tool cover -html=cover_all.out -o coverage-reports/index.html
          mv cover_all.out coverage-reports/

      - name: Upload Html report
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: coverage-html
          path: coverage-reports
          if-no-files-found: error