name: Merge Code Coverage
on:
  workflow_call:
    inputs:
      artifact_pattern:
        description: 'Artifact name pattern'
        required: false
        type: string
        default: 'cover_*'
      threshold:
        description: 'Coverage threshold'
        required: false
        type: number
        default: 0

permissions:
  actions: write
  contents: read  

jobs:
  merged_coverage:
    runs-on: ${{ vars.BUILD_CONTAINER_DISTRO_VERSION }}

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Download all coverage artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: ${{ inputs.artifact_pattern }}
          path: reports

      - name: Merge coverage profiles
        run: |
          go run github.com/wadey/gocovmerge reports/**/covprofile_*.out > cover_all.out

      - name: Check Code Coverage
        id: check-coverage
        uses: vladopajic/go-test-coverage@f190f667e23b4441202d0bab0f8c2e7bce8925b6 # v2.18.4
        continue-on-error: true
        with:
          config: ./.testcoverage.yml
          threshold-total: ${{ inputs.threshold }}

      - name: Show coverage summary
        if: always()
        run: |
          {
            echo "**Total coverage:** ${{ steps.check-coverage.outputs.total-coverage }}%"
            echo
            echo "<details><summary><strong>Detailed report</strong></summary>"
            echo
            echo '```text'
            echo '${{ steps.check-coverage.outputs.report }}' | jq -r .
            echo '```'
            echo "</details>"
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Generate Html report
        run: |
          mkdir -p coverage-reports
          go tool cover -html=cover_all.out -o coverage-reports/index.html
          mv cover_all.out coverage-reports/

      - name: Upload Html report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage-html
          path: coverage-reports
          if-no-files-found: error